# Generated by Django 5.2.6 on 2025-09-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id_detalle_factura', models.IntegerField(db_column='id_detalle_factura', primary_key=True, serialize=False)),
                ('cantidad_detalle_factura', models.IntegerField(blank=True, db_column='cantidad_detalle_factura', null=True)),
                ('precio_unitario_detalle_factura', models.DecimalField(blank=True, db_column='precio_unitario_detalle_factura', decimal_places=2, max_digits=10, null=True)),
                ('subtotal_detalle_factura', models.DecimalField(blank=True, db_column='subtotal_detalle_factura', decimal_places=2, max_digits=10, null=True)),
                ('iva_detalle_factura', models.DecimalField(blank=True, db_column='iva_detalle_factura', decimal_places=2, max_digits=10, null=True)),
                ('total_detalle_factura', models.DecimalField(blank=True, db_column='total_detalle_factura', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'detalle_factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.IntegerField(db_column='id_empresa', primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(blank=True, db_column='nombre_empresa', max_length=100, null=True)),
                ('nit_empresa', models.CharField(blank=True, db_column='nit_empresa', max_length=15, null=True, unique=True)),
                ('direccion_empresa', models.CharField(blank=True, db_column='direccion_empresa', max_length=150, null=True)),
                ('telefono_empresa', models.CharField(blank=True, db_column='telefono_empresa', max_length=15, null=True)),
                ('correo_empresa', models.CharField(blank=True, db_column='correo_empresa', max_length=100, null=True)),
                ('regimen_empresa', models.CharField(choices=[('Simplificado', 'Simplificado'), ('Comun', 'Común'), ('Especial', 'Especial')], db_column='regimen_empresa', default='Comun', max_length=15)),
                ('representante_legal', models.CharField(blank=True, db_column='representante_legal', max_length=100, null=True)),
                ('fecha_creacion_empresa', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion_empresa')),
            ],
            options={
                'db_table': 'emprpesa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.IntegerField(db_column='id_factura', primary_key=True, serialize=False)),
                ('fecha_factura', models.DateField(blank=True, db_column='fecha_factura', null=True)),
                ('metodo_pago_factura', models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia')], db_column='metodo_pago_factura', max_length=15, null=True)),
                ('cufe_factura', models.CharField(blank=True, db_column='cufe_factura', max_length=255, null=True, unique=True)),
                ('sutotal_factura', models.DecimalField(blank=True, db_column='sutotal_factura', decimal_places=2, max_digits=10, null=True)),
                ('iva_total_factura', models.DecimalField(blank=True, db_column='iva_total_factura', decimal_places=2, max_digits=10, null=True)),
                ('total_factura', models.DecimalField(blank=True, db_column='total_factura', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialFactura',
            fields=[
                ('id_historial_factura', models.IntegerField(db_column='id_historial_factura', primary_key=True, serialize=False)),
                ('fecha_de_evento', models.DateTimeField(auto_now_add=True, db_column='fecha_de_evento')),
                ('evento_historial_factura', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], db_column='evento_historial_factura', max_length=10, null=True)),
                ('observacion_historial_factura', models.TextField(blank=True, db_column='observacion_historial_factura', null=True)),
            ],
            options={
                'db_table': 'historial_factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.IntegerField(db_column='id_inventario', primary_key=True, serialize=False)),
                ('stock_actual_inventario', models.IntegerField(db_column='stock_actual_inventario', default=0)),
                ('stock_minimo_inventario', models.IntegerField(db_column='stock_minimo_inventario', default=1)),
                ('fecha_actualizacion_inventario', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion_inventario')),
                ('codigo_barras_inventario', models.CharField(blank=True, db_column='codigo_barras_inventario', max_length=100, null=True, unique=True)),
                ('imagen_inventario', models.CharField(blank=True, db_column='imagen_inventario', max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(db_column='id_producto', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, db_column='nombre_producto', max_length=50, null=True)),
                ('categoria_producto', models.CharField(blank=True, choices=[('Dispositivo', 'Dispositivo'), ('Auricular', 'Auricular'), ('Cargador', 'Cargador')], db_column='categoria_producto', max_length=20, null=True)),
                ('modelo_producto', models.CharField(blank=True, db_column='modelo_producto', max_length=50, null=True)),
                ('capacidad_producto', models.IntegerField(blank=True, db_column='capacidad_producto', null=True)),
                ('color_producto', models.CharField(blank=True, db_column='color_producto', max_length=20, null=True)),
                ('descripcion_producto', models.TextField(blank=True, db_column='descripcion_producto', null=True)),
                ('precio_producto', models.DecimalField(blank=True, db_column='precio_producto', decimal_places=2, max_digits=10, null=True)),
                ('codigo_barras_producto', models.CharField(blank=True, db_column='codigo_barras_producto', max_length=100, null=True, unique=True)),
                ('iva_producto', models.DecimalField(blank=True, db_column='iva_producto', decimal_places=2, max_digits=10, null=True)),
                ('imagen_producto', models.CharField(blank=True, db_column='imagen_producto', max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(blank=True, db_column='nombre_usuario', max_length=30, null=True)),
                ('segundo_nombre_usuario', models.CharField(blank=True, db_column='segundo_nombre_usuario', max_length=30, null=True)),
                ('apellido_usuario', models.CharField(blank=True, db_column='apellido_usuario', max_length=30, null=True)),
                ('segundo_apellido_usuario', models.CharField(blank=True, db_column='segundo_apellido_usuario', max_length=30, null=True)),
                ('tipo_documento_usuario', models.CharField(choices=[('cc', 'Cédula de ciudadanía'), ('ce', 'Cédula de extranjería'), ('pa', 'Pasaporte'), ('ppt', 'PPT'), ('nit', 'NIT'), ('cif', 'CIF'), ('ruc', 'RUC')], db_column='tipo_documento_usuario', default='cc', max_length=3)),
                ('numero_documento_usuario', models.CharField(db_column='numero_documento_usuario', max_length=15, unique=True)),
                ('correo_electronico_usuario', models.CharField(db_column='correo_electronico_usuario', max_length=100, unique=True)),
                ('contraseña_usuario', models.CharField(blank=True, db_column='contraseña_usuario', max_length=100, null=True)),
                ('direccion_usuario', models.CharField(blank=True, db_column='direccion_usuario', max_length=100, null=True)),
                ('telefono_usuario', models.CharField(blank=True, db_column='telefono_usuario', max_length=15, null=True)),
                ('rol_usuario', models.CharField(blank=True, choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('cliente', 'Cliente')], db_column='rol_usuario', max_length=10, null=True)),
                ('fecha_creacion_usuario', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion_usuario')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
