# Generated by Django 5.2.4 on 2025-10-06 05:24

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('nit_empresa', models.CharField(max_length=15, unique=True)),
                ('direccion_empresa', models.CharField(max_length=150)),
                ('telefono_empresa', models.CharField(max_length=15)),
                ('correo_empresa', models.EmailField(max_length=100)),
                ('regimen_empresa', models.CharField(choices=[('Simplificado', 'Simplificado'), ('Comun', 'Común'), ('Especial', 'Especial')], default='Comun', max_length=15)),
                ('representante_legal', models.CharField(max_length=100)),
                ('fecha_creacion_empresa', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('segundo_nombre_usuario', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido_usuario', models.CharField(max_length=30)),
                ('segundo_apellido_usuario', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_documento_usuario', models.CharField(choices=[('cc', 'Cédula de ciudadanía'), ('ce', 'Cédula de extranjería'), ('pa', 'Pasaporte'), ('ppt', 'Permiso por protección temporal'), ('nit', 'NIT'), ('cif', 'CIF'), ('ruc', 'RUC')], default='cc', max_length=5)),
                ('numero_documento_usuario', models.CharField(max_length=15, unique=True)),
                ('correo_electronico_usuario', models.EmailField(max_length=100, unique=True)),
                ('direccion_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_usuario', models.CharField(blank=True, max_length=15, null=True)),
                ('rol_usuario', models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('cliente', 'Cliente')], max_length=10)),
                ('fecha_creacion_usuario', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistorialFactura',
            fields=[
                ('id_historial_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_de_evento', models.DateTimeField(auto_now_add=True)),
                ('evento_historial_factura', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], max_length=10)),
                ('observacion_historial_factura', models.TextField(blank=True, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.factura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
