# Generated by Django 5.2.4 on 2025-10-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialFactura',
        ),
    ]
