# Generated by Django 5.2.6 on 2025-09-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empresa',
            table='empresa',
        ),
    ]
