# Generated by Django 5.2.4 on 2025-10-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_historialfactura'),
        ('core', '0002_usuario_bloqueado_hasta_usuario_intentos_fallidos_and_more'),
    ]

    operations = [
    ]
