# Generated by Django 5.2.6 on 2025-09-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='defaultuser', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
