# Generated by Django 5.2.4 on 2025-10-09 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20251009_1519'),
        ('core', '0003_merge_20251009_1538'),
    ]

    operations = [
    ]
