# Generated by Django 5.2.6 on 2025-09-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras_producto',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color_producto',
            field=models.CharField(choices=[('negro', 'Negro'), ('blanco', 'Blanco'), ('dorado', 'Dorado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion_producto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='iva_producto',
            field=models.DecimalField(decimal_places=2, default=19.0, editable=False, max_digits=10),
        ),
    ]
