# Generated by Django 5.2.6 on 2025-09-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_producto_codigo_barras_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='imagen_inventario',
            field=models.ImageField(blank=True, null=True, upload_to='inventario/'),
        ),
    ]
