# Generated by Django 5.2.6 on 2025-09-19 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('categoria_producto', models.CharField(choices=[('Dispositivo', 'Dispositivo'), ('Auricular', 'Auricular'), ('Cargador', 'Cargador')], max_length=20)),
                ('modelo_producto', models.CharField(max_length=50)),
                ('capacidad_producto', models.CharField(choices=[('No Aplica', 'No Aplica'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB')], max_length=20)),
                ('color_producto', models.CharField(choices=[('negro', 'Negro'), ('blanco', 'Blanco'), ('dorado', 'Dorado')], max_length=20)),
                ('descripcion_producto', models.TextField(blank=True, null=True)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_barras_producto', models.CharField(blank=True, max_length=100, unique=True)),
                ('iva_producto', models.DecimalField(decimal_places=2, default=19.0, editable=False, max_digits=10)),
                ('imagen_producto', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('stock_actual_inventario', models.IntegerField(default=0)),
                ('stock_minimo_inventario', models.IntegerField(default=1)),
                ('fecha_actualizacion_inventario', models.DateTimeField(auto_now=True)),
                ('codigo_barras_inventario', models.CharField(max_length=100, unique=True)),
                ('imagen_inventario', models.ImageField(blank=True, null=True, upload_to='inventario/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
