# Generated by Django 5.2.4 on 2025-09-26 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_emisor', models.CharField(max_length=255)),
                ('nit_emisor', models.CharField(max_length=50)),
                ('nombre_receptor', models.CharField(max_length=255)),
                ('nit_receptor', models.CharField(max_length=50)),
                ('correo_cliente', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(default='Pendiente', max_length=30)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('fecha_factura', models.DateField(default=datetime.date.today)),
                ('metodo_pago_factura', models.CharField(default='Efectivo', max_length=15)),
                ('cufe_factura', models.CharField(default='TEMP', max_length=255, unique=True)),
                ('sutotal_factura', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva_total_factura', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_factura', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente_id', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'facturas_factura',
            },
        ),
    ]
