# Generated by Django 5.2.4 on 2025-10-09 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialFactura',
            fields=[
                ('id_historial_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_de_evento', models.DateTimeField(auto_now_add=True)),
                ('evento_historial_factura', models.CharField(choices=[('CREADA', 'Factura creada'), ('ACTUALIZADA', 'Factura actualizada'), ('ELIMINADA', 'Factura eliminada'), ('ENVIADA', 'Factura enviada')], max_length=20)),
                ('observacion_historial_factura', models.TextField(blank=True, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.factura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
